version: '3.3'

services:
  # Приложение spring-boot
  app:
    container_name: template-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cn01jcev3ddc73bvb0o0-a.oregon-postgres.render.com:5432/test_cesv
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: L4maEvrnYhGFPifP4x2X1igzcAzx48qd
    networks:
      - backend

  # База данных
  db:
    image: postgres:14.5-alpine
    container_name: template-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=test_cesv
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=L4maEvrnYhGFPifP4x2X1igzcAzx48qd
    ports:
      - "5432:5432"
    networks:
      - backend

  # веб-приложение adminer для postgres
  admin:
    image: adminer
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: