version: '3.3'

services:
  # Приложение spring-boot
  app:
    container_name: template-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testApp?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
    networks:
      - backend

  # База данных
  db:
    image: postgres:14.5-alpine
    container_name: template-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=testApp
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - "5432:5432"
    networks:
      - backend

  # веб-приложение adminer для postgres
  admin:
    image: adminer
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: