version: '3.3'

services:
  # Приложение spring-boot
  app:
    container_name: template-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-prod-us-east-2-1.cluster-cfi5vnucvv3w.us-east-2.rds.amazonaws.com:5432/my-test-app-777-main-db-0545bec2f521f4e66?useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: my-test-app-777-main-db-0545bec2f521f4e66
      SPRING_DATASOURCE_PASSWORD: MKueHDZ2ArmmapQaFewhrJczUp2tSS
    networks:
      - backend

  # База данных
  db:
    image: postgres:14.5-alpine
    container_name: template-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=testApp
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - "5432:5432"
    networks:
      - backend

  # веб-приложение adminer для postgres
  admin:
    image: adminer
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: