spring:
  datasource:
    username: my-test-app-777-main-db-0545bec2f521f4e66
    password: MKueHDZ2ArmmapQaFewhrJczUp2tSS
    url: jdbc:postgresql://user-prod-us-east-2-1.cluster-cfi5vnucvv3w.us-east-2.rds.amazonaws.com:5432/my-test-app-777-main-db-0545bec2f521f4e66
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/migrations/db.migrations-master.xml
