spring:
  datasource:
    username: root
    password: toor
    url: jdbc:postgresql://localhost:5432/testApp
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/migrations/db.migrations-master.xml
